### ISSUE TITLE
sa4ss template

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pfmc-assessments/petrale#1]
Unfortunately, I just updated {sa4ss} so the files that you have a from the previous cycle and they will not compile. So, this issue serves as a reminder for @iantaylor-NOAA to update them or I can update them if you want and submit a pull request. My suggestion would be to save the new introduction elsewhere. Remove the docs directory and run draft again and then move the introduction back in.

**Comment by iantaylor-NOAA** [comment]
Thanks for the help @kellijohnson-NOAA. I installed the latest {sa4ss}, deleted all the files in `doc`, and re-ran `sa4ss::draft()`. Then I copied over the trivial changes we had made to the files and committed the changes in a36acb6b1844c6dbe05e48867ab036255ee3c14b.

However, I'm getting this error when running `bookdown::render_book()`
```
! LaTeX Error: File `pdflscape.sty' not found.
! Emergency stop.
```

I see that it tried and failed to install the package, and installing manually also fails:
```
> tinytex::tlmgr_install('pdflscape.sty')
tlmgr install pdflscape.sty
tlmgr.pl: package repository https://ctan.math.illinois.edu/systems/texlive/tlnet (not verified: valid signature with expired key)
tlmgr.pl install: package pdflscape.sty not present in repository.
tlmgr.pl: action install returned an error; continuing.
tlmgr.pl: An error has occurred. See above messages. Exiting.
```

Adding the `pdflscape.sty` file manually to `doc` created this error instead `! Package pdflscape Error: Neither pdfTeX nor PostScript driver found.`, so the package is presumably more than just the file.

I should also note that I also just updated from R 4.1.2 to R 4.2.2, so maybe that had an impact too.

**Comment by kellijohnson-NOAA** [comment]
It appears that you should leave off the `.sty` from the name of the package. I know when I run the command line version to install the package the following works
```
tlmgr install pdflscape
```

**Comment by iantaylor-NOAA** [comment]
Buried among the messages was a note that I should update tinytex via a command like `tinytex::reinstall_tinytex(repository = "illinois")`
Doing that allowed the missing package to get installed properly and the pdf is now building again on my computer.
